### PR TITLE
fix: focus behaviour

### LINKED ISSUE #518: Comportamento inatteso della pseudoclasse :focus
## Comportamento atteso
Il focus sugli elementi del DOM è visibile solo quando si naviga la pagina con la tastiera

## Comportamento attuale
Il focus è visibile anche quando l'elemento del DOM viene cliccato
image

### PR DESCRIPTION
**Pull request by emilioSp**
## Descrizione
Questa PR fixes #518

### CODE REVIEW

**Comment by emilioSp** [comment]
> @emilioSp before asking for a review, may I ask you to rebase this PR with the current `master`?
> 
> Thank you

Hi @astagi I have updated the branch with master. If the review passes, you can squash and merge to ignore the merge branch commit

**Comment by astagi** [comment]
> > @emilioSp before asking for a review, may I ask you to rebase this PR with the current `master`?
> > Thank you
> 
> Hi @astagi I have updated the branch with master. If the review passes, you can squash and merge to ignore the merge branch commit

Thank you @emilioSp

**Comment by astagi** [comment]
@emilioSp trying your code I noticed that focus on buttons disappears after clicking, although on Bootstrap buttons keep their focus (https://getbootstrap.com/docs/4.6/components/buttons/)

**Review by astagi — CHANGES_REQUESTED** [review]
Restringere campo di azione.

**Comment by astagi** [comment]
Closed by #595

**Pull request closed without merging**
